g <- new("graphNEL", nodes=c("a","b","c", "d"), edgemode="directed")
g <- addEdge(graph=g, from="a", to="b")
g <- addEdge(graph=g, from="a", to="c")
g <- addEdge(graph=g, from="a", to="d")
g <- addEdge(graph=g, from="b", to="c")
g <- addEdge(graph=g, from="b", to="d")
g <- addEdge(graph=g, from="b", to="a")
g <- addEdge(graph=g, from="c", to="d")
g <- addEdge(graph=g, from="c", to="a")
g <- addEdge(graph=g, from="c", to="b")
g <- addEdge(graph=g, from="d", to="a")
g <- addEdge(graph=g, from="d", to="b")
g <- addEdge(graph=g, from="d", to="c")
#eulerian(g, weighted=F)
#print(is_even_graph(g))



g <- new("graphNEL", nodes=as.character(1:10), edgemode="directed")
g <- addEdge(graph=g, from="1", to="10")
g <- addEdge(graph=g, from="2", to="1")
g <- addEdge(graph=g, from="2", to="6")
g <- addEdge(graph=g, from="3", to="2")
g <- addEdge(graph=g, from="4", to="2")
g <- addEdge(graph=g, from="5", to="4")
g <- addEdge(graph=g, from="6", to="5")
g <- addEdge(graph=g, from="6", to="8")
g <- addEdge(graph=g, from="7", to="9")
g <- addEdge(graph=g, from="8", to="7")
g <- addEdge(graph=g, from="9", to="6")
g <- addEdge(graph=g, from="10", to="3")
#eulerian(g, weighted=F)
