source("code/utility.motif.R")

inputFile <- "data/profile_most_data-3.txt"
inputs <- readLines(con=inputFile, n=2, warn=F)
dna <- inputs[1]
numbers <- strsplit(inputs[2], " ")[[1]]
k <- as.integer(numbers[1])
profile <- read.table(file=inputFile, header=T, skip=2, sep="", quote="", comment.char="")


# Given a profile matrix Profile, we can evaluate the probability of every k-mer in a string Text and find a Profile-most probable k-mer in Text, i.e., a k-mer that was most likely to have been generated by Profile. For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT. Indeed, every other 12-mer in this string has probability 0.
# 
# Profile-most Probable k-mer Problem: Find a Profile-most probable k-mer in a string.
# Input: A string Text, an integer k, and a k × 4 matrix Profile.
# Output: A Profile-most probable k-mer in Text.

profileMostProbableKmer <- function(dna, k, profile){
  kmers <- getKmers(text=dna, k=k, unique=T)
  probabilities <- sapply(kmers, probabilityOfDna, profile)
  maxProbableKmerIndex <- which(probabilities==max(probabilities))
  mostProbableKmer <- kmers[maxProbableKmerIndex]
  return(mostProbableKmer)
}

#debug(probabilityOfString)
mostProbableKmer <- profileMostProbableKmer(dna=dna, k=k, profile=profile)
cat(mostProbableKmer)